image: docker:latest

stages:
  - build

variables:
  DOCKER_REGISTRY: 'luisnabais/heartbeat-client'
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64/v8"

services:
  - docker:dind

container-build:
  stage: build
  before_script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker buildx create --use
    - docker buildx build
      --provenance=false
      --platform ${BUILDX_PLATFORMS}
      --tag ${CI_REGISTRY_IMAGE}:latest
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      --tag ${DOCKER_REGISTRY}:${CI_COMMIT_TAG}
      --push
      .
  rules:
    - if: $CI_COMMIT_TAG