image: docker:latest

stages:
  - tag
  - build

variables:
  DOCKER_REGISTRY: 'luisnabais/heartbeat-client'
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64/v8"

services:
  - docker:dind

auto-tag:
  stage: tag
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - export VERSION=$(cat VERSION)
    - echo "Versão: $VERSION"
    - |
      if git rev-parse "$VERSION" >/dev/null 2>&1; then
        echo "Tag $VERSION já existe, a pipeline não vai criar nova tag."
        exit 0
      fi
    - git config --global user.email "ci@example.com"
    - git config --global user.name "CI Bot"
    - git tag "$VERSION"
    - git push origin "$VERSION"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - VERSION

container-build:
  stage: build
  before_script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker buildx create --use
    - docker buildx build
      --provenance=false
      --platform ${BUILDX_PLATFORMS}
      --tag ${CI_REGISTRY_IMAGE}:latest
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      --tag ${DOCKER_REGISTRY}:${CI_COMMIT_TAG}
      --push
      .
  rules:
    - if: $CI_COMMIT_TAG